coarse grid
Parametrisierung PARXC PARYC TMAXC
      8   18   0   4     1       NEL NVT NMT NVE NBCT
DCORVG
   0    0
   1    0
   2    0
   3    0
   4    0
   5    0
   6    0
   7    0
   8    0
   9    0
   10   0
   11   0
   12   0
   13   0
   14   0
   15   0
   16   0
   17   0
KVERT
   1  2  3  18
   3  4  17 18
   4  5  16 17
   5  6  15 16
   6  7  14 15
   7  8  13 14
   8  9  12 13
   9  10 11 12
KNPR
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 
KMM
1 4
